name: Trigger auto deployment for aerocloud-authentication

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aerocloud-authentication-AutoDeployTrigger-8ff54d76-d8ed-4e0b-b550-092edad9c282.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AEROCLOUDAUTHENTICATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AEROCLOUDAUTHENTICATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AEROCLOUDAUTHENTICATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.AEROCLOUDAUTHENTICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AEROCLOUDAUTHENTICATION_REGISTRY_PASSWORD }}
          containerAppName: aerocloud-authentication
          resourceGroup: aerocloudxyz
          imageToBuild: antonio0806/aerocloud-authentication:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


