name: Trigger auto deployment for aerocloudxyz-authentication

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/aerocloudxyz-authentication-AutoDeployTrigger-0da14a6a-1488-4478-a3ba-800f53c936d0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AEROCLOUDXYZAUTHENTICATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AEROCLOUDXYZAUTHENTICATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AEROCLOUDXYZAUTHENTICATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.AEROCLOUDXYZAUTHENTICATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AEROCLOUDXYZAUTHENTICATION_REGISTRY_PASSWORD }}
          containerAppName: aerocloudxyz-authentication
          resourceGroup: aerocloudxyz
          imageToBuild: antonio0806/aerocloudxyz-authentication:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


